---
version: "3.4"

services:
  python-rdf-workshop:
    image: localhost/python-rdf-workshop:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment: 
      FLASK_DEBUG: 1
    volumes: 
      - ./api:/app/api
    ports:
      - 5000:5000 
    # Add environment variable to set FLASK_DEBUG on 1
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#environment for more info
    # Add volume to mount local api folder to /app/api folder in container
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes for more info
    # Make application accessible on port 5000
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more info

  # Add virtuoso (the redpencil image) as a service, with port mapping, and a volume map

  virtuoso:
    image: redpencil/virtuoso
    ports:
      - 8890:8890
    volumes:
      - /tmp/data:/data


  
  emberjs:
    build:
      context: ./my-ember-js-app
      dockerfile: docker/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./my-ember-js-app:/usr/src/app

